#!/usr/bin/env bash
# Simula o Supabase remoto da LEP antes do alinhamento (usado por db-test.sh):
#   • fundação aplicada manualmente pelo SQL Editor (fora do histórico do CLI);
#   • core.editais criada pelo painel (id bigint, colunas diferentes, um edital antigo);
#   • 20260928 executada até o erro "column review_status ... does not exist".
set -euo pipefail
cd "$(dirname "$0")/../../.."
PSQL=(psql "$DB_URL" -v ON_ERROR_STOP=1 -X -q)

"${PSQL[@]}" -f supabase/migrations/20260925120000_core_foundation.sql
"${PSQL[@]}" <<'SQL'
insert into core.organizations (name, slug) values ('LEP Filmes', 'lep-filmes');
create table core.editais (
  id bigint generated by default as identity primary key,
  title text not null,
  status text,
  deadline date,
  created_at timestamptz default now()
);
insert into core.editais (title, status, deadline) values ('Edital cadastrado pelo painel', 'aberto', '2026-12-01');
SQL
# Trecho da 20260928 executado antes do erro (pior caso: comandos anteriores confirmados).
sed '/^comment on column core.editais.review_status/,$d' supabase/migrations/20260928120000_monitoramento.sql \
  | "${PSQL[@]}"
